package:
  name: pandera
  version: "0.3.0"

source:
  git_rev: 0.3.0
  git_url: https://github.com/pandera-dev/pandera.git

build:
  noarch: python

requirements:
  build:
    - python >=3.5
    - numpy
    - pandas
    - scipy
    - wrapt
  run:
    - python >=3.5
    - numpy
    - pandas
    - scipy
    - wrapt

test:
  imports:
    - pandera

about:
  home: https://github.com/pandera-dev/pandera
  license: MIT
  summary: 'Light-weight and flexible validation for pandas data structures.'
  description: |
     Pandas data structures hide a lot of information, and explicitly
     validating them in production-critical or reproducible research
     settings is a good idea.
  doc_url: https://pandera.readthedocs.io/
